# Generated by Django 5.0.7 on 2024-07-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_drink_drinks_drink_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinks',
            name='price',
            field=models.IntegerField(),
        ),
    ]
